export const INITLOGIN = 'initlogin'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const TITLE = 'title'
export const CHANGE = 'change'
export const ADDTODO = 'addtodo'
export const DELTODO = 'deltodo'